<a href="https://colab.research.google.com/github/priyanshu7466/Python/blob/main/ML/Bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/19_Bagging/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
X = df.drop(['Outcome'],axis='columns')
y = df.Outcome

In [7]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [8]:
268/500

0.536

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,stratify=y,random_state=10)

In [11]:
len(X_train)

576

In [12]:
len(X_test)

192

In [13]:
y_train.value_counts()

0    375
1    201
Name: Outcome, dtype: int64

In [14]:
201/375

0.536

In [15]:
y_test.value_counts()

0    125
1     67
Name: Outcome, dtype: int64

In [16]:
67/125

0.536

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [18]:
scores = cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.68831169, 0.64935065, 0.67532468, 0.77777778, 0.73856209])

In [19]:
scores.mean()

0.7058653764536118

In [20]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    estimator= DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train,y_train)
bag_model.oob_score_

0.7534722222222222

In [21]:
bag_model.score(X_test,y_test)

0.7760416666666666

In [22]:
bag_model = BaggingClassifier(
    estimator= DecisionTreeClassifier(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model,X,y,cv=5)
scores

array([0.75324675, 0.72727273, 0.74675325, 0.82352941, 0.73856209])

In [23]:
scores.mean()

0.7578728461081402

In [24]:
from sklearn.ensemble import RandomForestClassifier
scores = cross_val_score(RandomForestClassifier(n_estimators=50),X,y,cv=5)
scores.mean()

0.7669892199303965

# Exercise

In [25]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/19_Bagging/Exercise/heart.csv")
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [26]:
df = pd.get_dummies(df,drop_first=True)
df

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0     40        140          289          0    172      0.0             0   
1     49        160          180          0    156      1.0             1   
2     37        130          283          0     98      0.0             0   
3     48        138          214          0    108      1.5             1   
4     54        150          195          0    122      0.0             0   
..   ...        ...          ...        ...    ...      ...           ...   
913   45        110          264          0    132      1.2             1   
914   68        144          193          1    141      3.4             1   
915   57        130          131          0    115      1.2             1   
916   57        130          236          0    174      0.0             1   
917   38        138          175          0    173      0.0             0   

     Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0        1                  1                  0                 0   
1        0                  0                  1                 0   
2        1                  1                  0                 0   
3        0                  0                  0                 0   
4        1                  0                  1                 0   
..     ...                ...                ...               ...   
913      1                  0                  0                 1   
914      1                  0                  0                 0   
915      1                  0                  0                 0   
916      0                  1                  0                 0   
917      1                  0                  1                 0   

     RestingECG_Normal  RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  \
0                    1              0                 0              0   
1                    1              0                 0              1   
2                    0              1                 0              0   
3                    1              0                 1              1   
4                    1              0                 0              0   
..                 ...            ...               ...            ...   
913                  1              0                 0              1   
914                  1              0                 0              1   
915                  1              0                 1              1   
916                  0              0                 0              1   
917                  1              0                 0              0   

     ST_Slope_Up  
0              1  
1              0  
2              1  
3              0  
4              1  
..           ...  
913            0  
914            0  
915            0  
916            0  
917            1  

[918 rows x 16 columns]

In [27]:
X = df.drop(['HeartDisease'],axis='columns')
y = df.HeartDisease

In [28]:
from sklearn.svm import SVC

In [29]:
y.value_counts()

1    508
0    410
Name: HeartDisease, dtype: int64

In [30]:
410/508

0.8070866141732284

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,random_state=30)

In [32]:
len(X_train)

688

In [33]:
len(X_test)

230

In [34]:
y_train.value_counts()

1    381
0    307
Name: HeartDisease, dtype: int64

In [35]:
307/381

0.8057742782152231

In [36]:
y_test.value_counts()

1    127
0    103
Name: HeartDisease, dtype: int64

In [37]:
103/127

0.8110236220472441

In [45]:
scores_svm = cross_val_score(SVC(),X,y,cv=5)
scores_svm.mean()

0.686231884057971

In [54]:
bag_model_svm = BaggingClassifier(
    estimator= SVC(),
    n_estimators=100,
    max_samples = 0.8,
    oob_score=True,
    random_state=10
)
bag_model_svm.fit(X_train,y_train)
bag_model_svm.oob_score_

0.7209302325581395

In [55]:
bag_model_svm.score(X_test,y_test)

0.717391304347826

In [56]:
scores = cross_val_score(bag_model_svm,X,y,cv=5)
scores.mean()

0.6829472558802566

As we can see above, using bagging in case of SVM doesn't make much difference in terms of model accuracy. Bagging is effective when we have high variance and instable model such as decision tree. Let's explore how bagging changes the performance for a decision tree classifier.

In [48]:
scores_tree = cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores_tree.mean()

0.7166785459729152

In [49]:
bag_model_tree = BaggingClassifier(
    estimator= DecisionTreeClassifier(),
    max_samples = 0.8,
    n_estimators = 100,
    oob_score=True,
    random_state=10
)
bag_model_tree.fit(X_train,y_train)
bag_model.oob_score_

0.7209302325581395

In [50]:
bag_model_tree.score(X_test,y_test)

0.8956521739130435

In [52]:
scores = cross_val_score(bag_model_tree,X,y,cv=5)
scores.mean()

0.7972796388690901

We can see that with bagging the score improved from 71.66% to 79.72%

In [57]:
scores = cross_val_score(RandomForestClassifier(),X,y,cv=5)
scores.mean()

0.8223627940128297

Random forest gave even a better performance with 82.23% as score. Underneath it used bagging where it sampled not only data rows but also the columns (or features)