<a href="https://colab.research.google.com/github/priyanshu7466/Python/blob/main/ML/GradientDescent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/3_gradient_descent/Exercise/test_scores.csv")
df.head()

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83

In [88]:
x = np.array(df['math'])
y = np.array(df['cs'])
import math

In [89]:
def gd(x,y):
  m = b = 0
  iterations = 1000000
  rate = 0.0002
  n = len(x)
  cost_previous = 0
  for i in range(iterations):
    y_predicted = m*x + b
    cost = (1/n)*sum(val**2 for val in (y - y_predicted))
    dm = (-2/n)*sum(x*(y - y_predicted))
    db = (-2/n)*sum(y - y_predicted)
    m = m - rate*dm
    b = b - rate*db
    if math.isclose(cost,cost_previous,rel_tol=1e-20):
      break
    cost_previous = cost
#    print("m {}, b {}, cost {}, iterations {}".format(m,b,cost,i))
  return m,b

In [90]:
gd(x,y)

(1.0177381667350405, 1.9150826165722297)

In [91]:
from sklearn import linear_model

In [92]:
reg = linear_model.LinearRegression()
reg.fit(df[['math']],df.cs)

LinearRegression()

In [93]:
reg.coef_

array([1.01773624])

In [94]:
reg.intercept_

1.9152193111569034

# Saving Model

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [4]:
df = pd.read_csv('/content/home_price.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [6]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

In [9]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [11]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [18]:
import joblib

In [19]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [20]:
mj = joblib.load('model_joblib')

In [21]:
mj.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [22]:
mj.coef_

array([135.78767123])

In [23]:
mj.intercept_

180616.43835616432