<a href="https://colab.research.google.com/github/priyanshu7466/Python/blob/main/ML/KFold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [6]:
lr = LogisticRegression()
svm = SVC()
rf = RandomForestClassifier()

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [13]:
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [14]:
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [15]:
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [17]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [19]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [25]:
get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test)

0.9611111111111111

In [27]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [36]:
lr_score = []
svm_score = []
rf_score = []

for train_index, test_index in folds.split(digits.data,digits.target):
  X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
  lr_score.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train, X_test, y_train, y_test))
  svm_score.append(get_score(SVC(gamma='auto'),X_train, X_test, y_train, y_test))
  rf_score.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

In [37]:
lr_score

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [38]:
svm_score

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [39]:
rf_score

[0.9365609348914858, 0.9398998330550918, 0.9365609348914858]

In [40]:
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [42]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.93155259, 0.95492487, 0.91819699])

In [44]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=3)
np.average(score1)

0.8430717863105176

In [46]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)
np.average(score2)

0.9376739009460211

In [47]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=3)
np.average(score3)

0.9382303839732887

In [48]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target,cv=3)
np.average(score4)

0.9326655537006121

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 50 trees in random forest gives best result.

# Exercise

In [49]:
from sklearn.datasets import load_iris
iris = load_iris()

In [58]:
lr_score = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)
np.average(lr_score)

0.9533333333333333

In [52]:
svm_score = cross_val_score(SVC(),iris.data,iris.target,cv=3)
np.average(svm_score)

0.96

In [64]:
rf_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)
np.average(rf_score)

0.9666666666666667

In [54]:
from sklearn.tree import DecisionTreeClassifier

In [55]:
tree_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
np.average(tree_score)

0.9666666666666667

Best Score so far is using RandomForest or DecisionTree Classifier