<a href="https://colab.research.google.com/github/priyanshu7466/Python/blob/main/ML/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Survival Prediction

In [132]:
import numpy as np
import pandas as pd

In [133]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [134]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [135]:
target = df.Survived
inputs = df.drop(['Survived'],axis='columns')

In [136]:
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [137]:
dummies = pd.get_dummies(df.Sex)
dummies

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [138]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [139]:
inputs.drop(['Sex'],axis='columns',inplace=True)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [140]:
inputs.Age.isna()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [141]:
inputs['Age'] = inputs.Age.fillna(inputs.Age.median())
inputs.head(10)

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1
5       3  28.0   8.4583       0     1
6       1  54.0  51.8625       0     1
7       3   2.0  21.0750       0     1
8       3  27.0  11.1333       1     0
9       2  14.0  30.0708       1     0

In [142]:
inputs.Age.isna()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [143]:
from sklearn.naive_bayes import GaussianNB

In [144]:
model = GaussianNB()

In [145]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.25)

In [146]:
len(X_train)

668

In [147]:
len(X_test)

223

In [148]:
model.fit(X_train,y_train)

GaussianNB()

In [149]:
model.score(X_test,y_test)

0.7623318385650224

In [150]:
X_test[:10]

Pclass   Age      Fare  female  male
34        1  28.0   82.1708       0     1
77        3  28.0    8.0500       0     1
357       2  38.0   13.0000       1     0
181       2  28.0   15.0500       0     1
812       2  35.0   10.5000       0     1
696       3  44.0    8.0500       0     1
683       3  14.0   46.9000       0     1
811       3  39.0   24.1500       0     1
705       2  39.0   26.0000       0     1
763       1  36.0  120.0000       1     0

In [151]:
model.predict(X_test[:10])

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [152]:
y_test[:10]

34     0
77     0
357    0
181    0
812    0
696    0
683    0
811    0
705    0
763    1
Name: Survived, dtype: int64

In [153]:
model.predict_proba(X_test[:10])

array([[6.39369379e-01, 3.60630621e-01],
       [9.90213788e-01, 9.78621166e-03],
       [3.03364570e-02, 9.69663543e-01],
       [9.80423448e-01, 1.95765517e-02],
       [9.81256469e-01, 1.87435310e-02],
       [9.91388561e-01, 8.61143907e-03],
       [9.82681260e-01, 1.73187396e-02],
       [9.91146520e-01, 8.85347972e-03],
       [9.81351436e-01, 1.86485638e-02],
       [4.28142510e-05, 9.99957186e-01]])

In [154]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(GaussianNB(),X_train,y_train,cv=5)
np.average(score)

0.7890584670631804

# Email Spam Filter

In [155]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [156]:
df.groupby(['Category']).describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [157]:
df['spam'] = df.Category.apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [162]:
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam)

In [163]:
from sklearn.feature_extraction.text import CountVectorizer

In [164]:
v = CountVectorizer()

In [165]:
X_train_count = v.fit_transform(X_train.values)

In [166]:
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [167]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [168]:
model.fit(X_train_count,y_train)

MultinomialNB()

In [170]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [171]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9856424982053122

**sklearn pipeline**

In [172]:
from sklearn.pipeline import Pipeline

In [175]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [176]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [177]:
clf.score(X_test,y_test)

0.9856424982053122

In [178]:
clf.predict(emails)

array([0, 1])

# Exercise

In [179]:
from sklearn.datasets import load_wine
wine = load_wine()

In [180]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [184]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [185]:
df = pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [194]:
df['target'] = wine.target

In [195]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [196]:
targets = df.target
inputs = df.drop(['target'],axis='columns')

In [197]:
inputs.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [198]:
X_train, X_test, y_train, y_test = train_test_split(inputs,targets,test_size=0.2)

In [199]:
len(X_train)

142

In [200]:
len(X_test)

36

In [201]:
Model = GaussianNB()
Model.fit(X_train,y_train)

GaussianNB()

In [202]:
Model.score(X_test,y_test)

0.9722222222222222

In [203]:
scores = cross_val_score(GaussianNB(),X_train,y_train,cv=5)
scores

array([0.93103448, 0.96551724, 0.92857143, 0.96428571, 1.        ])

In [204]:
np.average(scores)

0.9578817733990148

In [205]:
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [206]:
model.score(X_test,y_test)

0.7222222222222222

In [207]:
score = cross_val_score(MultinomialNB(),X_train,y_train,cv=5)
score

array([0.82758621, 0.82758621, 0.89285714, 0.85714286, 0.85714286])

In [208]:
np.average(score)

0.8524630541871921

We can clearly see here that Gaussian Classifier performs better.