<a href="https://colab.research.google.com/github/priyanshu7466/Python/blob/main/Deep_Learning/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot("amazing restaurant",50)

[48, 38]

In [9]:
vocab_size = 50
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[14, 22],
 [48, 38],
 [26, 7],
 [11, 38, 44],
 [37, 8, 46],
 [4, 22],
 [9, 8, 48],
 [14, 47],
 [14, 24],
 [34, 16]]

In [10]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[14 22  0  0]
 [48 38  0  0]
 [26  7  0  0]
 [11 38 44  0]
 [37  8 46  0]
 [ 4 22  0  0]
 [ 9  8 48  0]
 [14 47  0  0]
 [14 24  0  0]
 [34 16  0  0]]


In [11]:
embedded_vector_size = 5
model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size,embedded_vector_size,input_length=max_length,name="embedding"))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1,activation='sigmoid'))

In [12]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              250       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 271 (1.06 KB)
Trainable params: 271 (1.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.fit(X,y,epochs=50,verbose=0)

In [15]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 157ms/step - loss: 0.6395 - accuracy: 0.7000


0.699999988079071

In [16]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [17]:
weights[14]

array([-0.07391351, -0.04632399,  0.00730025,  0.0650334 ,  0.05078588],
      dtype=float32)

In [18]:
weights[48]

array([ 0.00602367, -0.09704757,  0.05842573,  0.02863201,  0.06017395],
      dtype=float32)

In [19]:
weights[44]

array([-0.01673026,  0.04494263, -0.00828623, -0.0134489 , -0.01840264],
      dtype=float32)